# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 13:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pmsApp.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('Id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name should only contain characters', regex='^[a-zA-Z\\s]*$')])),
                ('LastName', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name should only contain characters', regex='^[a-zA-Z\\s]*$')])),
                ('UserName', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Name should only contain characters', regex='^[a-zA-Z\\s]*$')])),
                ('MailId', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(8)])),
                ('PhoneNo', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Invalid Phone Number', regex='^[789]\\d{9}$')])),
            ],
            options={
                'ordering': ['UserName'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name should only contain characters', regex='^[a-zA-Z\\s]*$')])),
                ('MiddleName', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name should only contain characters', regex='^[a-zA-Z\\s]*$')])),
                ('LastName', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Name should only contain characters', regex='^[a-zA-Z\\s]*$')])),
                ('DateOfBirth', models.DateField()),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=10)),
                ('FlatNo', models.CharField(max_length=15)),
                ('State', models.CharField(choices=[('ben', 'Bangalore'), ('mys', 'Mysore'), ('hub', 'Hubballi'), ('mdy', 'Mandya')], default='a', max_length=30)),
                ('City', models.CharField(choices=[('ap', 'Andhra Pradesh'), ('mh', 'Maharashtra'), ('ka', 'Karnataka')], default='a', max_length=30)),
                ('PlaceOfBirth', models.CharField(max_length=30)),
                ('ApplicantId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pmsApp.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddressProof', models.ImageField(upload_to=pmsApp.models.get_user_image_folder)),
                ('BirthCertificate', models.ImageField(upload_to=pmsApp.models.get_user_image_folder)),
                ('PaymentReceipt', models.ImageField(upload_to=pmsApp.models.get_user_image_folder)),
                ('ApplicantId', models.OneToOneField(default='ecb7f2f0ca0c4df59848d92722464da6', on_delete=django.db.models.deletion.CASCADE, to='pmsApp.Applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='u', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=500)),
                ('ApplicantId', models.OneToOneField(default='ecb7f2f0ca0c4df59848d92722464da6', on_delete=django.db.models.deletion.CASCADE, to='pmsApp.Applicant')),
            ],
        ),
    ]
