# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsApp', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='FlatNo',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(default='u', max_length=1),
        ),
    ]
