# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmsApp', '0004_auto_20180408_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='ApplicationId',
            new_name='ApplicatioId',
        ),
    ]
