# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import pmsApp.helpers.models_helper
import pmsApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pmsApp', '0009_auto_20180409_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='AddressProof',
            field=models.ImageField(upload_to=pmsApp.helpers.models_helper.get_address_folder, validators=[pmsApp.validators.validate_file_extension, pmsApp.validators.file_size]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='BirthCertificate',
            field=models.ImageField(upload_to=pmsApp.helpers.models_helper.get_birth_certificate_folder, validators=[pmsApp.validators.validate_file_extension, pmsApp.validators.file_size]),
        ),
        migrations.AlterField(
            model_name='documents',
            name='PaymentReceipt',
            field=models.ImageField(upload_to=pmsApp.helpers.models_helper.get_payment_receipt_folder, validators=[pmsApp.validators.validate_file_extension, pmsApp.validators.file_size]),
        ),
    ]
