# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-08 21:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsApp', '0010_auto_20180409_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MailId', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
            options={
                'ordering': ['MailId'],
            },
        ),
    ]
