# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import pmsApp.helpers.models_helper
import pmsApp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('pmsApp', '0011_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='Photo',
            field=models.ImageField(default='sagarstorm/a.jpg', upload_to=pmsApp.helpers.models_helper.get_photo_folder, validators=[pmsApp.validators.validate_file_extension, pmsApp.validators.file_size_photo]),
        ),
    ]
