# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-09 19:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmsApp', '0012_documents_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DepartmentId', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)])),
                ('Division', models.CharField(choices=[('bn', 'Bangalore-North'), ('bs', 'Bangalore-South'), ('be', 'Bangalore-East'), ('bbmp', 'Bangalore-BBMP')], default='bn', max_length=30)),
                ('District', models.CharField(choices=[('ben', 'Bangalore'), ('mys', 'Mysore'), ('hub', 'Hubballi'), ('mdy', 'Mandya')], default='ben', max_length=30)),
                ('State', models.CharField(choices=[('ap', 'Andhra Pradesh'), ('mh', 'Maharashtra'), ('ka', 'Karnataka')], default='ka', max_length=30)),
                ('MailId', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(8)])),
            ],
        ),
    ]
